[package]
name = "wasabi"
version = "0.1.0"
authors = ["Steve Akinyemi <appcypher@outlook.com>"]
edition = "2018"

[[bin]]
name = "wacc"
path = "bin/wacc.rs"

[[bin]]
name = "waxx" # Cargo doesn't like `wa++` :/
path = "bin/wa++.rs"

[features]
debug = []
